// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  card: dynamic(() => import('./Card')),
  footer_block: dynamic(() => import('./FooterBlock')),
  form_field: dynamic(() => import('./FormField')),
  hero: dynamic(() => import('./Hero')),
  image_gallery: dynamic(() => import('./Gallery')),
  page_section: dynamic(() => import('./PageSection')),
  social_button: dynamic(() => import('./SocialButton')),
  table: dynamic(() => import('./Table')),
};
