import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import localFont from 'next/font/local';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from 'next';

import theme from './theme';

import Main from '@/components/Main';

import './globals.css';

const hertine = localFont({
  src: [
    {
      path: './fonts/hertine/Hertine.otf',
      weight: '500',
    },
  ],
  display: 'swap',
  variable: '--font-hertine',
});

const neueEinstellung = localFont({
  src: [
    {
      path: './fonts/neue-einstellung/NeueEinstellung-ExtraLight.otf',
      weight: '100',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Light.otf',
      weight: '200',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Thin.otf',
      weight: '300',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Regular.otf',
      weight: '400',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Medium.otf',
      weight: '500',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Medium.otf',
      weight: '500',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-SemiBold.otf',
      weight: '600',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-Bold.otf',
      weight: '700',
    },
    {
      path: './fonts/neue-einstellung/NeueEinstellung-ExtraBold.otf',
      weight: '800',
    },
  ],
  display: 'swap',
  variable: '--font-neue-einstellung',
});

const cormorantGaramond = localFont({
  src: [
    {
      path: './fonts/cormorant-garamond/CormorantGaramond-Light.ttf',
      weight: '300',
    },
    {
      path: './fonts/cormorant-garamond/CormorantGaramond-Regular.ttf',
      weight: '400',
    },
    {
      path: './fonts/cormorant-garamond/CormorantGaramond-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/cormorant-garamond/CormorantGaramond-SemiBold.ttf',
      weight: '600',
    },
    {
      path: './fonts/cormorant-garamond/CormorantGaramond-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-cormorant-garabond',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body className={`${cormorantGaramond.variable} ${neueEinstellung.variable} ${hertine.variable}`}>
            <Main>{children}</Main>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
